services:
  mongo:
    image: mongo:latest
    container_name: "baazarbot_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "baazarbot"
      MONGO_INITDB_ROOT_PASSWORD: "baazarbot"
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "baazarbot_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always

volumes:
  mongo_data:
  qdrant_data:

networks:
  local:
    driver: bridge
