[tool.poetry]
name = "baazarbot"
version = "0.1.0"
description = ""
authors = ["Sassan Owssia <sassan.owssia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
