parameters:
  links:
    # EcoIran News
    ## Macroeconomics
    - https://ecoiran.com/%D8%A8%D8%AE%D8%B4-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF-%DA%A9%D9%84%D8%A7%D9%86-79
    ## Stock Market
    - https://ecoiran.com/%D8%A8%D8%AE%D8%B4-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D8%A8%D9%88%D8%B1%D8%B3-157
    ## Gold and Currency Market
    - https://ecoiran.com/%D8%A8%D8%AE%D8%B4-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D8%B7%D9%84%D8%A7-%D8%A7%D8%B1%D8%B2-80
    ## Housing and Urban
    - https://ecoiran.com/%D8%A8%D8%AE%D8%B4-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D9%85%D8%B3%DA%A9%D9%86-%D8%B4%D9%87%D8%B1%DB%8C-147
    # Rules and regulations
    # - https://rc.majlis.ir/fa/law/search?page=1
    # ICCIMA reports
    # - https://iccima.ir/%DA%AF%D8%B2%D8%A7%D8%B1%D8%B4-%D9%87%D8%A7/
